crm/urls.py
from django.urls import path
from .views import DashboardAdminView,  acceso_denegado, logout_view
from . import views
urlpatterns = [
    path('ad_dashboard/', DashboardAdminView.as_view(), name='dashboard_admin'),
    #path('as_dashboard/', DashboardAsesorView.as_view(), name='dashboard_asesor'),
    path('acceso_denegado/', views.acceso_denegado, name='acceso_denegado'),
   # path('error/', acceso_denegado, name='404'),
    path('logout/', logout_view, name='logout'),

    ###------- admins clients urls ------------##
    path('admins_clients/',views.AdminsClientList.as_view(),name='client_list'),
    path('admins_clients/details/<int:pk>', views.AdminsClientDetails.as_view(), name= 'client_detail'),
    path('admins_clients/<int:pk>/edit/', views.AdminsClientUpdate.as_view(), name='client_update'),
    path('admins_clients/<int:pk>/delete/', views.AdminsClientDelete.as_view(), name='client_delete'),
    ###------- end admins clients urls --------####

    ## --------- admins budgets urls --------- ###
    path('admins_budgets/',views.AdminBudgetList.as_view(),name = 'budget_list'),
    path('admins_budgets/details/<int:pk>',views.AdminBudgetDetail.as_view(), name = 'budget_details'),
    path('admins_budgets/create/',views.AdminBudgetCreateView.as_view(), name='budget_create'),
    path('admins_budgets/edit/<int:pk>',views.AdminBudgetEdit.as_view(), name='budget_edit'),
    path('admins_budgets/delete/<int:pk>',views.AdminBudgetDeleteView.as_view(),name='budget_delete'),
    ## ----------- end admins budgets urls ------- ###

    path('admins_closedSales/',views.AdminClosedSalesList.as_view(),name = 'closedSales_list'),
    path('admins_closedSales/details/<int:pk>',views.AdminclosedSalesDetail.as_view(),name='closedSales_details'),
    path('admins_closedSales/edit/<int:pk>',views.AdminsclosedSalesUpdate.as_view(),name='closedSales_edit'),
    path('admins_closedSales/delete/<int:pk>',views.AdminclosedSaleDelete.as_view(),name='closedSales_delete'),
]

webproyect/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('login/',include('login.urls')),
    path('crm/',include('crm.urls'))
    
]

crm/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator  # Import MaxValueValidator
from django.contrib.auth.models import User  # Import User
from decimal import Decimal 
import logging
logger = logging.getLogger(__name__)

class Client(models.Model):
    first_name = models.CharField(max_length=60, verbose_name="Nombre", help_text="Nombre del cliente")
    paternal_last_name = models.CharField(max_length=60, verbose_name="Apellido paterno", help_text="Primer apellido")
    maternal_last_name = models.CharField(max_length=60, verbose_name="Apellido materno", help_text="Segundo apellido")
    email = models.EmailField(unique=True, verbose_name="Correo electrónico")
    phone_number = models.CharField(
        max_length=15,
        verbose_name="Número de teléfono",
        help_text="Número de teléfono con código de área"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Última actualización")

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ["first_name", "paternal_last_name"]

    def __str__(self):
        return f"{self.first_name} {self.paternal_last_name} {self.maternal_last_name}"


class Budget(models.Model):
    STATE = [
        ('pendiente', 'Pendiente'),
        ('aceptado', 'Aceptado'),
        ('rechazado', 'Rechazado'),
    ]

    emission_date = models.DateField()
    client = models.ForeignKey('Client', on_delete=models.CASCADE)
    itinerary = models.CharField(max_length=200)  
    cod_airline = models.CharField(max_length=200)  
    reserv_system = models.CharField(max_length=200)  
    beeper = models.CharField(max_length=200)  
    base_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(99999999.99)])
    emisor_cost = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(99999999.99)])
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(99999999.99)])
    special_services = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    vendor = models.ForeignKey(User, on_delete=models.CASCADE)
    provider = models.CharField(max_length=200)
    state = models.CharField(max_length=10, choices=STATE, default='pendiente')

    cost_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sale_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cielo_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    vendor_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def calculate_cost_price(self):
        return (self.base_price or 0) + (self.emisor_cost or 0)

    def calculate_sale_fee(self):
        return (self.sale_price or 0) - self.calculate_cost_price() + (self.special_services or 0)

    def calculate_cielo_fee(self):
        sale_fee = self.calculate_sale_fee()
        return sale_fee - (Decimal(sale_fee) * Decimal('0.13')) if sale_fee else 0

    def calculate_vendor_fee(self):
        return self.calculate_sale_fee() - self.calculate_cielo_fee()

    def save(self, *args, **kwargs):
        try:
            creating_closed_sale = False
            
            if self.pk:
                old_budget = Budget.objects.get(pk=self.pk)
                if old_budget.state != "aceptado" and self.state == "aceptado":
                    creating_closed_sale = True

            self.cost_price = self.calculate_cost_price()
            self.sale_fee = self.calculate_sale_fee()
            self.cielo_fee = self.calculate_cielo_fee()
            self.vendor_fee = self.calculate_vendor_fee()

            super().save(*args, **kwargs)

            if creating_closed_sale:
                closed_sale, created = closedSales.objects.get_or_create(
                    budget=self,
                    defaults={
                        'client': self.client,
                        'vendor': self.vendor,
                        'sales_price': self.sale_price,
                        'fee_sale': self.sale_fee,
                        'fee_cielo': self.cielo_fee,
                        'fee_vendor': self.vendor_fee,
                        'paid': "Pendiente"
                    }
                )
                if not created:
                    logger.info(f"ClosedSale ya existía para el presupuesto {self.pk}, actualizando datos...")
                    closed_sale.client = self.client
                    closed_sale.vendor = self.vendor
                    closed_sale.sales_price = self.sale_price
                    closed_sale.fee_sale = self.sale_fee
                    closed_sale.fee_cielo = self.cielo_fee
                    closed_sale.fee_vendor = self.vendor_fee
                    closed_sale.save()

        except Exception as e:
            logger.error(f"Error al guardar el presupuesto o crear la venta cerrada: {e}")
            raise

class closedSales(models.Model):
    budget = models.OneToOneField('Budget', on_delete=models.CASCADE, related_name='venta')
    client = models.ForeignKey('Client', on_delete=models.CASCADE)
    vendor = models.ForeignKey(User, on_delete=models.CASCADE)
    sales_price = models.DecimalField(max_digits=10, decimal_places=2)
    fee_sale = models.DecimalField(max_digits=10, decimal_places=2)
    fee_cielo = models.DecimalField(max_digits=10, decimal_places=2)
    fee_vendor = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.CharField(max_length=20)
    date_sale = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Venta de {self.client} - {self.date_sale}"

crm/templates/admins/admins_budgtes/budget_confirm_delete.html
{% extends 'base2.html' %}

{% block title %}Eliminar Presupuesto{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg border-0 rounded-lg p-4">
                <div class="card-header bg-danger text-white text-center">
                    <h3 class="mb-0">Eliminar Presupuesto</h3>
                </div>
                <div class="card-body text-center">
                    <p class="mb-4">
                        ¿Estás seguro de que deseas eliminar presupuesto a  
                        <strong>{{ budget.itinerary }}</strong> de 
                        <strong>{{ budget.client }}</strong>? 
                        Esta acción no se puede deshacer.
                    </p>
                    
                    <form method="post">
                        {% csrf_token %}
                        
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-danger mx-2">Confirmar</button>
                            <a href="{% url 'budget_list' %}" class="btn btn-secondary mx-2">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
   
{% endblock %}

crm/templates/admins/admins_budgtes/budget_detail.html
{% extends 'base2.html' %}

{% block title %}Detalles del Presupuesto{% endblock %}

{% block content %}
<div class="card shadow-sm mt-4">
    <div class="card-header">
        <h4 class="card-title">Detalles del Presupuesto</h4>
    </div>
    <div class="card-body">
        <p><strong>Fecha de Emisión:</strong> {{ budget.emission_date }}</p>
        <p><strong>Vendedor:</strong> {{ budget.vendor.username }}</p>
        <p><strong>Cliente:</strong> {{ budget.client.first_name }} {{ budget.client.paternal_last_name }} {{ budget.client.maternal_last_name }}</p>
        <p><strong>Itinerario:</strong> {{ budget.itinerary }}</p>

        <table class="table custom-table mt-3">
            <thead>
                <tr>
                    <th>Concepto</th>
                    <th>Monto</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Precio Base</td>
                    <td>${{ budget.base_price }}</td>
                </tr>
                <tr>
                    <td>Costo Emisión</td>
                    <td>${{ budget.base_price }}</td>
                </tr>
                <tr>
                    <td>Servicios Especiales</td>
                    <td>${{ budget.special_services }}</td>
                </tr>
                <tr>
                    <td>Precio de Venta</td>
                    <td>${{ budget.sale_price }}</td>
                </tr>
                <tr>
                    <td>Fee Cielo</td>
                    <td>${{ budget.cielo_fee }}</td>
                </tr>
                <tr>
                    <td>Fee Vendedor</td>
                    <td>${{ budget.vendor_fee }}</td>
                </tr>
            </tbody>
        </table>

        <p><strong>Estado:</strong> {{ budget.get_state_display }}</p>
        <a class="btn btn-secondary" href="{% url 'budget_list' %}" role="button" aria-label="Volver">Volver</a>
        <a class="btn btn-info" href="{% url 'budget_edit' budget.id  %}" role="button" aria-label="Modificar presupuesto">Modificar</a>
    </div>

</div>

<style>
    .card {
        border-radius: 10px;
        overflow: hidden;
        margin-top: 20px;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-header {
        background-color: #114fac;
        color: white;
        text-align: center;
        padding: 10px;
        font-size: 18px;
        font-weight: bold;
    }

    .card-body p {
        font-size: 16px;
        line-height: 1.6;
    }

    /* Estilos para la tabla */
    .custom-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    .custom-table th {
        background-color: #114fac;
        color: white;
        text-align: left;
        padding: 10px;
        font-weight: bold;
    }

    .custom-table td {
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }

    .custom-table tr:nth-child(even) {
        background-color: #f8f9fa;
    }

    .custom-table tr:hover {
        background-color: #e9ecef;
    }

    .btn {
        border-radius: 5px;
        padding: 8px 15px;
        font-size: 14px;
    }

    .btn-secondary {
        background-color: #6c757d;
        color: white;
    }

    .btn-info {
        background-color: #17a2b8;
        color: white;
    }
</style>

{%endblock%}

crm/templates/admins/admins_budgtes/budget_form.html
{% extends 'base2.html' %}

{% block title %}
    {% if form.instance.pk %}
        Editar Presupuesto - {{ form.instance.client }}
    {% else %}
        Nuevo Presupuesto
    {% endif %}
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow">
                <div class="card-header bg-primary text-white text-center">
                    <h2 class="mb-0">
                        {% if form.instance.pk %}Editar Información del Presupuesto{% else %}Registrar Nuevo Presupuesto{% endif %}
                    </h2>
                </div>
                <div class="card-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        
                        <div class="row">
                            {% for field in form.visible_fields %}
                                <div class="col-md-4 mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.errors %}
                                        <div class="invalid-feedback">
                                            {% for error in field.errors %}{{ error }}{% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                                {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                            {% endfor %}
                        </div>

                       
                        <div class="d-flex justify-content-between mt-4">
                            <a href="{% url 'budget_list' %}" class="btn btn-danger">Cancelar</a>
                            <button type="submit" class="btn btn-primary">
                                {% if form.instance.pk %}Actualizar{% else %}Guardar{% endif %} Presupuesto
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const inputs = {
            basePrice: document.getElementById('{{ form.base_price.id_for_label }}'),
            emisorCost: document.getElementById('{{ form.emisor_cost.id_for_label }}'),
            salePrice: document.getElementById('{{ form.sale_price.id_for_label }}'),
            specialServices: document.getElementById('{{ form.special_services.id_for_label }}'),
        };
        
        const calculatedFields = {
            costPrice: document.getElementById('calculated-cost-price'),
            saleFee: document.getElementById('calculated-sale-fee'),
            cieloFee: document.getElementById('calculated-cielo-fee'),
        };

        function updateCalculatedFields() {
            const values = Object.fromEntries(
                Object.entries(inputs).map(([key, input]) => [key, parseFloat(input.value) || 0])
            );

            // Realiza los cálculos
            const costPrice = values.basePrice + values.emisorCost;
            const saleFee = values.salePrice - costPrice + values.specialServices;
            const cieloFee = saleFee * 0.87; // Calcula Fee de Cielo

            // Actualiza los campos calculados
            calculatedFields.costPrice.value = costPrice.toFixed(2);
            calculatedFields.saleFee.value = saleFee.toFixed(2);
            calculatedFields.cieloFee.value = cieloFee.toFixed(2);
        }

        // Agrega un listener para cada input que calcule los valores al cambiar
        Object.values(inputs--).forEach(input => input.addEventListener('input', updateCalculatedFields));

        // Calcula los valores por defecto cuando se carga la página
        updateCalculatedFields();
    });
</script>
{% endblock %}

crm/templates/admins/admins_budgtes/budget_list.html
{% extends 'base2.html' %}
{% block title %}Lista de Presupuestos{% endblock %}

{% block content %}
    <h1>Presupuestos</h1>
    <a class="btn btn-primary" href="{% url 'budget_create' %}" role="button"> Crear Nuevo Presupuesto</a>
    {% if budgets %}
    <table class="table table-hover table-bordered shadow-sm mt-4">
        <thead class="table-primary">
            <tr>
                <th>Fecha</th>
                <th>Cliente</th>
                <th>Vendedor</th>
                <th>Precio de Venta</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for budget in budgets %}
            <tr>
                <td>{{ budget.emission_date }}</td>
                <td>{{ budget.client }}</td>
                <td>{{ budget.vendor }}</td>
                <td>{{ budget.sale_price }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'budget_details' budget.id %}" role="button" aria-label="Ver presupuesto">Ver</a>
                    <a class="btn btn-info" href="{% url 'budget_edit' budget.id %}"role="button" aria-label="Modificar presupuesto">Modificar</a>
                    <a class="btn btn-danger" href="{% url 'budget_delete' budget.id %}" role="button" aria-label="Eliminar presupuesto">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginación -->
    {% if is_paginated %}
    <div class="pagination mt-4">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-secondary" aria-label="Página anterior">Anterior</a>
            {% endif %}
            <span class="page-current">
                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-secondary" aria-label="Página siguiente">Siguiente</a>
            {% endif %}
        </span>
    </div>

    {% endif %}
    
{% endif %}

<style>
    .table {
        border-radius: 10px;
        overflow: hidden;
    }

    .table thead {
        background: #003a92;
        color: rgb(8, 8, 8);
        font-weight: bold;
    }

    .table tbody tr:hover {
        background: #8c98a5;
        transition: 0.3s ease-in-out;
        color: rgb(0, 0, 0);
        font-weight: bold;
    }

    .table td,
    .table th {
        padding: 12px;
        text-align: center;
        vertical-align: middle;
    }

    .btn {
        border-radius: 5px;
        padding: 6px 12px;
    }
</style>
{% endblock %}